language: ruby
rvm:
  - 2.1.1
bundler_args: --without production
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -c 'create database travis_ci_development;' -U postgres
    - cp config/database.travis.yml config/database.yml
